# Generated by Django 3.1 on 2020-08-15 15:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200402_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newsmodel'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 15, 15, 45, 3, 658773, tzinfo=utc)),
        ),
    ]
